#define PI             3.1415926536
#define TWO_PI         (2.0 * PI)
#define GRAVITY        981         // In Unreal unit
#define HALF_SQRT_TWO  0.7071068
#define SQUARE(x)      (x * x)

#define DECLARE_TEXTURE_SIZE_WITH_NAME(Texture, TextureSize)  \
    float2 TextureSize; Texture.GetDimensions(TextureSize.x, TextureSize.y);

#define DECLARE_TEXTURE_SIZE(Texture) DECLARE_TEXTURE_SIZE_WITH_NAME(Texture, Texture##Size)
